-- Begin the PL/SQL block to drop tables
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
        'CURRENCYEXCHANGERATE', 'TRANSACTIONIDEXCHANGERATE', 'TRANSACTIONIDCURRENCY',
        'TRANSACTIONIDTIMESTAMP', 'TRANSACTIONIDAMOUNT', 'TRANSACTIONIDDATAREQUESTID',
        'TRANSACTIONIDUSERID', 'DATABELONGCATEGORY', 'DATACATEGORY', 'DATAREQUEST',
        'COMPANY', 'USERGENERATEDREPORTDETAILS', 'REPORTGENERATEDON', 'TRANSPARENCYREPORT',
        'USERACTIVITYDETAILS', 'USERACTIVITYTYPE', 'ACTIVITYTIMESTAMP', 'ACTIVITY',
        'COMPANYNAMESIZE', 'COMPANYNAMEINDUSTRY', 'CORPORATEUSER', 'INDIVIDUALUSERNAME',
        'INDIVIDUALUSER', 'USEREMAILPASSWORD', 'USEREMAILUSERNAME', 'USERS'
    )) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- Drop sequences if they exist
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE DataRequest_seq';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Ignore if the sequence does not exist
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE User_seq';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Ignore if the sequence does not exist
END;
/